export enum Cuisine {
  TUNISIAN = 'Tunisian',
  LEBANESE = 'Lebanese',
  MIDDLE_EAST = 'Middle Eastern',
  INDIAN = 'Indian',
  TURKISH = 'Turkish',
  ITALIAN = 'Italian',
  FRENCH = 'French',
  SYRIAN = 'Syrian',
  JAPANESE = 'Japanese',
  TAIWANESE = 'Taiwanese',
  CHINESE = 'Chinese',
  MEXICAN = 'Mexican',
  VEGETARIAN = 'Vegetarian',
  FUSION = 'Fusion',
  KOREAN = 'Korean',
  ASIAN = 'Asian',
}

export enum MealType {
  BREAKFAST = 'Breakfast',
  BRUNCH = 'Brunch',
  LUNCH = 'Lunch',
  DINNER = 'Dinner',
  LATE_DINNER = 'Late Dinner',
  COCKTAIL = 'Cocktail',
  SNACK = 'Snack',
  DESSERT = 'Dessert',
  BEVERAGE = 'Beverage',
  BREAKING_FAST = 'Breaking fast',
  OTHER = 'Other',
}

export enum RestaurantFeature {
  WITH_FRIENDS = 'With friends',
  DINNER_AND_SHOW = 'Dinner and Show',
  ALL_YOU_CAN_EAT_BUFFET = 'All You Can Eat Buffet',
  BIRTHDAY = 'Birthday',
  BISTRO = 'Bistro',
  BISTRONOMIC = 'Bistronomic',
  CONTEMPORARY_CUISINE = 'Contemporary Cuisine',
  FINE_DINING = 'Fine Dining',
  FROM_MARKET = 'From Market',
  GARDEN = 'Garden',
  GIFT_CARDS = 'Gift Cards',
  GOOD_FOR_BUSINESS_LUNCH = 'Good for a Business Lunch',
  GOOD_FOR_FAMILIES = 'Good for Families',
  GOOD_FOR_GROUPS = 'Good for Groups',
  GREAT_VIEW = 'Great View',
  IN_THE_MOUNTAINS = 'In the Mountains',
  KID_FRIENDLY = 'Kid-Friendly',
  SEAFRONT = 'Seafront',
  ORGANIC = 'Organic',
  RESTAURANT_HOTEL = 'Restaurant Hotel',
  ROMANTIC = 'Romantic',
  SEMINAR = 'Seminar',
  TERRACE = 'Terrace',
  TRADITIONAL = 'Traditional',
  TRENDY = 'Trendy',
  WEDDING = 'Wedding',
  WINE_BAR = 'Wine Bar',
  OUTDOOR_SITTING = 'Outdoor Seating',
  LIVE_MUSIC = 'Live Music',
}

export enum RestaurantStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
}
